version: "3.8"

services:
  php:
    image : php:8.2-apache
    container_name: php8.2
    ports: 
      - "8000:80"
    volumes:
      - ./php:/var/www/html
    build : 
      context: .
      dockerfile: Dockerfile
  db:
    image : mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306
  phpma:
    image : phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80